[tool.poetry]
name = "robot-framework-project"
version = "0.1.0"
description = "Robot Framework Test Automation Project"
authors = ["OleksandrKaminskyi"]

[tool.poetry.dependencies]
python = "^3.12"
robotframework = "^7.0"
robotframework-seleniumlibrary = "^6.0"
requests = "^2.31"
pyyaml = "^6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"